baseURL = 'https://wonjongbot.github.io/wonjongbot_website_25'
languageCode = 'en-us'
title = 'wonjongbot'
theme = 'hugo-theme-console'
pygmentsStyle = "manni" #"native"

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = true

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn fast" 

  [[params.navlinks]]
  name = "home/"
  url = "/"

  # [[params.navlinks]]
  # name = "about/"
  # url = "about/"

  [[params.navlinks]]
  name = "posts/"
  url = "posts/"
  
  [[params.navlinks]]
  name = "projects/"
  url = "projects/"

  [[params.navlinks]]
  name = "cv/"
  url = "cv/"